version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/bakalarka
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

